name: Build

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        build-configuration: [Debug, Development, Shipping]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          lfs: true
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64
      - name: Setup
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: .\Setup.bat
      - name: Build
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: msbuild Renderwerk.sln /m /p:Configuration=${{matrix.build-configuration}} -fl -flp:logfile=Logs/Build-${{matrix.build-configuration}}.log
      - name: Test
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          cd ./Binaries/Engine/windows-${{matrix.build-configuration}}/EngineTests
          ./EngineTests.exe
      - name: Upload logs on failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: Windows-Build-${{matrix.build-configuration}}-Logs
          path: Logs/Build-${{matrix.build-configuration}}.log
